name: 上报 Bug
description: 使用中文进行 Bug 报告
labels: ['bug']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      options:
      - label: 我已经搜索了现有的 issues
        required: true
      - label: 我在提问题之前至少花费了 5 分钟来思考和准备
        required: true
      - label: 我已经认真且完整的阅读了 wiki
        required: true
      - label: 我已经认真检查了问题和网络环境无关（包括但不限于 Google 不可用，模型下载失败）
        required: true
      - label: 我已填写环境信息
        required: true
      - label: 我已上传原始文件，或确认该问题与原始文件无关
        required: true
      - label: 我确认此问题与本项目的 api 无关（在 api 文档写出来之前，不受理任何有关 api 使用的疑问！）
        required: true
  - type: markdown
    attributes:
      value: |
        感谢您使用本项目并反馈！
        请再次确认上述复选框所述的内容已经认真执行！
  - type: textarea
    id: environment
    attributes:
      label: 使用的环境（请务必说明 pdf2zh & BabelDOC 版本，缺少相关版本号的 issue 会被直接关闭）
      placeholder: |
          - **OS**: Ubuntu 24.10  
          - **Python**: 3.12.0  
          - **pdf2zh**: 2.0.0
          - **BabelDOC**: 0.3.69
      render: markdown
    validations:
      required: false
  - type: dropdown
    id: install
    attributes:
      label: 请选择安装方式
      options:
        - pip
        - exe
        - 源码
        - docker
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: 描述你的问题
      description: 简要描述你的问题
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 如何复现
      description: 重现该行为的步骤
      value: |
        1. 执行 '...'
        2. 选择 '....'
        3. 出现问题
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 简要描述你期望得到的反馈
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 相关 Logs
      description: 请复制并粘贴任何相关的日志输出。
      render: Text
    validations:
      required: false
  - type: textarea
    id: PDFfile
    attributes:
      label: 原始 PDF 文件
      description: |
        请尽可能提供原始的 PDF 文件，方便复现错误。（若该问题需要原始文件来复现，但您未提供，则 issue 会被直接关闭）
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 还有别的吗？
      description: |
        相关的配置？链接？参考资料？
        任何能让我们对你所遇到的问题有更多了解的东西。
    validations:
      required: false